openapi: 3.0.3
info: 
 title: OpenAPI Learning :) 
 description: |
 
   # About Us
    **sodales** ut _etiam_ sit `amet` nisl purus in mollis nunc sed id semper risus in hendrerit gravida rutrum quisque non tellus orci ac auctor augue mauris augue neque **gravida** in fermentum et sollicitudin ac orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras `fermentum` odio
    
   # Categories
     nisi <u>*vitae suscipit tellus mauris*</u> a diam maecenas sed enim ut sem viverra aliquet eget sit <u>amet tellus</u> cras adipiscing
    - mobiles
      - apple 
      - samsumg
    - laptops
    - tvs 
    - headphones
    - desktop
    
    ```
     public void method()
     {
        System.out.println("Hello world");
     }
    
    ```
  
   ## category2 
    phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet enim
     
 termsOfService: https://www.google.com   
 contact:
  name: Raj
  email: akks@gmail.com
  url: https://www.google.com   
 license: 
  name: name
  url: https://google.com
 version: 0.0.1
servers:
 - url: https://www.google.com
   description: my description
 - url: https://www.google.com
   description: my description
 - url: https://{username}.server.com:{port}/{version}
   variables: 
     username:
       default: demo       
       description: my description  
     port:
      enum:
       - "8443"
       - "443"
      default: "8443"  
      description: my description
     version: 
        default: v1  
        description: my version
   description: my description
paths: 
 /products:
  get:
    summary: list of all products
    description : |
     **Lorem** Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with `desktop` publishing software like Aldus PageMaker including versions of Lorem Ipsum.
    parameters: 
      - name: name
        in : query
        schema: 
         type: array
         items:
          type: string
        example: ["hello"] 
    responses: 
      '200':
        description: list of products
        content: 
         application/json:
          schema: 
           type: array
           items: 
            type: object
            properties: 
             productID:
              type: integer
             name:
              type: string
             price: 
              type: number
              format: double
             categoryName: 
               type: string
             quantity: 
               type: integer
               description: |
                 ***id volutpat*** lacus laoreet non curabitur gravida arcu ac tortor dignissim convallis `aenean` et tortor at risus viverra adipiscing at in tellus integer feugiat scelerisque <u>varius</u> morbi enim nunc faucibus

 
         
          
       
    
      
     
      
          
   
   
  
       
             
              
                        
             

  
             
           
           
          
          
      
  
     
    
 
   
 