openapi: 3.0.3
info: 
 title: my first open api
 description: my description 
 termsOfService:
 contact:
  name: 
  email: 
  url: 
 license: 
  name:
  url:
  version:    
 version: 1.0.2
paths: 
 /products: 
   get: 
    summary:
    description: 
    responses: 
      '200':
        description: list of products
            # content: 
            #    application/json:
            #     schema:
            #      type: integer
            #      minimum: 1 
            #      maximum: 100

            # content: 
            #  application/json:
            #   schema:
            #    type: string
            #    enum:
            #     - Alice
            #     - Bob
            #     - Carl

            #  content: 
            #   application/json:
            #    schema:
            #     type : array 
            #     minItems: 1
            #     maxItems: 10
            #     items: 
            #      type: integer

            # content: 
            #  application/json:
            #   schema:
            #    type: object
            #    properties:
            #     productName: 
            #      type: string
            #     productPrice: 
            #      type: number 
        

          
