security:
 - BasicAuth: []
 - BearerAuth: []
 - ApiKeyAuth: []
 - oAuth2AuthCode: 
    - read
    - write
    - admin
 - OpenId: 
    - read
    - write
    - admin
components: 
 parameters:    
 schemas:   
 responses:  
 securitySchemes: 
  BasicAuth: 
   type: http
   scheme: basic  
  BearerAuth:
   type: http
   scheme: bearer
   bearerFormat: JWT
  ApiKeyAuth:
   type: apiKey
   in: header
   name: X-API-KEY
  oAuth2AuthCode:
   type: oauth2
   flows:
    authorizationCode: 
     authorizationUrl: https://example.com/oauth/authorize
     tokenUrl: https://example.com/api/oauth.access
     scopes:
      read: Read only access
      write: Read write access
      admin: Admin access
  OpenId: 
   type: openIdConnect
   openIdConnectUrl: https://example.com/.well-known/openid-configuration
   
  